---
title: "Week 7, Day 2"
author: "Sarah Moore"
date: "`r Sys.Date()`"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, root.dir = "~/Users/sarahmoore/OneDrive - Northwestern University/Teaching_RA/2022_Fall_DataViz/lousy-graphs")

packages <- c("tidyverse", "reshape2", "fauxnaif", "gganimate", "ggthemes",
              "stringr", "gridExtra", "gifski", "png", "ggrepel", "scales",
              "lubridate", "paletteer", "GGally", "systemfonts", "extrafont",
              "colorspace", "sf", "rnaturalearth", "ggmap",
              "rnaturalearthdata", "paletteer", "srtingr", "haven")

lapply(packages, require, character.only = TRUE)

loadfonts(device = "all")

acled_asia <- read_csv("data/20102020_ACLED_Asia.csv")

countries_acled <- unique(acled_asia$country)
```


```{r continental asia map, include = T, eval = }

asia_continent <- ne_countries(country = countries_acled, returnclass = "sf")

# can append this data if we want to add labels 
#asia_continent <- cbind(asia_continent, st_coordinates(st_centroid(asia_continent$geometry)))

ggplot(data = asia_continent)+ 
  geom_sf(aes()) + 
  theme(
    panel.background = element_blank()
  )
```

```{r acled data explore, include = F, eval = T}

dim(acled_asia)

names(acled_asia)

unique(acled_asia$year) # 2010-2020 

unique(acled_asia$event_type) # 6 different types of events 

acled_asia %>%
  group_by(year, event_type) %>% 
  count()

```