project:
  type: website

website:
  title: "Sarah Moore's Example Blog for Poli Sci 390"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/sarah-moore/lousy-graphs
format:
  html:
    theme: litera
    css: styles.css



